//! Electricity flow — the future electrical simulation. Charge will travel through
//! blocks by their [`conductivity`](crate::block::CoreProperties::conductivity),
//! be generated by `HeatToElectricity` specials, and be banked by
//! `ElectricityStorage` ones; configuration blocks will route it by their layout.
//! None of that runs yet: this system is wired into the tick loop but gated off.
use crate::sim::Tick;
use crate::world::World;

/// Moves charge between conductive blocks (eventually). Inert until enabled.
pub struct ElectricalSystem {
    /// Off until propagation is implemented; the tick is wired but does nothing.
    enabled: bool,
}

impl ElectricalSystem {
    pub fn new() -> Self {
        Self { enabled: false }
    }

    /// How readily electricity enters the block at a world coordinate. The accessor
    /// the real propagation step will sweep over the conductive network — kept here
    /// to prove the derived block data is reachable from the simulation.
    fn conductivity_at(&self, world: &World, x: i32, y: i32, z: i32) -> u8 {
        let id = world.block_at(x, y, z);
        world.registry().block(id).core.conductivity
    }
}

impl Tick for ElectricalSystem {
    fn tick(&mut self, world: &mut World, _dt: f32) {
        if !self.enabled {
            return;
        }
        // TODO: flood charge along connected conductive blocks, source it from
        // HeatToElectricity specials, sink it into ElectricityStorage specials, and
        // route it through configuration-block layouts.
        let _ = self.conductivity_at(world, 0, 0, 0);
    }
}

impl Default for ElectricalSystem {
    fn default() -> Self {
        Self::new()
    }
}
