//! Crate-wide declarative macros.
//!
//! These cover the two patterns we expect to grow over time:
//! - [`voxels!`] — a block table that generates the [`Voxel`](crate::world::voxel::Voxel)
//!   enum and its property lookups, so adding a block type is a single line.
//! - [`axis!`] — a keyboard-driven movement axis (positive / negative / none),
//!   so adding a new control axis doesn't repeat the same `if`-ladder.
//!
//! Both macros use fully-qualified `::raylib::...` paths so they expand
//! correctly regardless of what the call site has imported.

/// Define a tri-state movement axis bound to two keys.
///
/// ```ignore
/// axis!(#[derive(Clone, Copy)] AxisX { Right = KEY_D, Left = KEY_A });
/// let dir = AxisX::sample(&rl); // Right / Left / None
/// let s = dir.signum();         // +1.0 / -1.0 / 0.0
/// ```
macro_rules! axis {
    ($(#[$meta:meta])* $name:ident { $pos:ident = $pkey:ident, $neg:ident = $nkey:ident }) => {
        $(#[$meta])*
        pub enum $name {
            $pos,
            $neg,
            None,
        }

        impl $name {
            /// Read this axis from the current keyboard state.
            pub fn sample(rl: &::raylib::prelude::RaylibHandle) -> Self {
                if rl.is_key_down(::raylib::prelude::KeyboardKey::$pkey) {
                    $name::$pos
                } else if rl.is_key_down(::raylib::prelude::KeyboardKey::$nkey) {
                    $name::$neg
                } else {
                    $name::None
                }
            }

            /// `+1.0` for the positive direction, `-1.0` for the negative, `0.0` for none.
            pub fn signum(&self) -> f32 {
                match self {
                    $name::$pos => 1.0,
                    $name::$neg => -1.0,
                    $name::None => 0.0,
                }
            }

            /// Whether a direction is being held this frame (not `None`).
            pub fn is_active(&self) -> bool {
                !matches!(self, $name::None)
            }
        }
    };
}
pub(crate) use axis;

/// Define the [`Voxel`](crate::world::voxel::Voxel) enum from a block table, generating
/// `is_solid` and `color` lookups. Each entry is one line: adding a block type
/// means adding a row here and nothing else.
///
/// ```ignore
/// voxels! {
///     Air   => { solid: false, color: (0, 0, 0, 0) },
///     Stone => { solid: true,  color: (128, 128, 128, 255) },
/// }
/// ```
macro_rules! voxels {
    ( $( $(#[$meta:meta])* $name:ident => { solid: $solid:expr, color: ($r:expr, $g:expr, $b:expr, $a:expr $(,)?) } ),* $(,)? ) => {
        /// A single block. `Air` is empty space; everything else is solid terrain.
        ///
        /// Generated by the [`voxels!`](crate::macros::voxels) macro.
        #[derive(Clone, Copy, PartialEq, Eq, Debug)]
        pub enum Voxel {
            $( $(#[$meta])* $name ),*
        }

        impl Voxel {
            /// Whether the block participates in collision and rendering.
            pub fn is_solid(self) -> bool {
                match self {
                    $( Voxel::$name => $solid ),*
                }
            }

            /// The colour used to draw this block.
            pub fn color(self) -> ::raylib::prelude::Color {
                match self {
                    $( Voxel::$name => ::raylib::prelude::Color::new($r, $g, $b, $a) ),*
                }
            }
        }
    };
}
pub(crate) use voxels;
