//! Crate-wide declarative macros.
//!
//! These cover the table-driven patterns we expect to grow over time:
//! - [`elements!`] — the built-in element table; generates the [`El`](crate::block::element)
//!   id handles and `builtin_elements()`, so adding a material is a single row.
//! - [`blocks!`] — the built-in block table; generates the [`Blk`](crate::block::registry)
//!   id handles and `register_builtins()` from element compositions.
//! - [`axis!`] — a keyboard-driven movement axis (positive / negative / none),
//!   so adding a new control axis doesn't repeat the same `if`-ladder.
//!
//! Both macros use fully-qualified `::raylib::...` paths so they expand
//! correctly regardless of what the call site has imported.

/// Define a tri-state movement axis bound to two keys.
///
/// ```ignore
/// axis!(#[derive(Clone, Copy)] AxisX { Right = KEY_D, Left = KEY_A });
/// let dir = AxisX::sample(&rl); // Right / Left / None
/// let s = dir.signum();         // +1.0 / -1.0 / 0.0
/// ```
macro_rules! axis {
    ($(#[$meta:meta])* $name:ident { $pos:ident = $pkey:ident, $neg:ident = $nkey:ident }) => {
        $(#[$meta])*
        pub enum $name {
            $pos,
            $neg,
            None,
        }

        impl $name {
            /// Read this axis from the current keyboard state.
            pub fn sample(rl: &::raylib::prelude::RaylibHandle) -> Self {
                if rl.is_key_down(::raylib::prelude::KeyboardKey::$pkey) {
                    $name::$pos
                } else if rl.is_key_down(::raylib::prelude::KeyboardKey::$nkey) {
                    $name::$neg
                } else {
                    $name::None
                }
            }

            /// `+1.0` for the positive direction, `-1.0` for the negative, `0.0` for none.
            pub fn signum(&self) -> f32 {
                match self {
                    $name::$pos => 1.0,
                    $name::$neg => -1.0,
                    $name::None => 0.0,
                }
            }

            /// Whether a direction is being held this frame (not `None`).
            pub fn is_active(&self) -> bool {
                !matches!(self, $name::None)
            }
        }
    };
}
pub(crate) use axis;

/// Define the built-in element table. Generates the [`El`] handle enum (each
/// variant's discriminant is its [`ElementId`](crate::block::element::ElementId),
/// fixed by declaration order) and a `builtin_elements()` constructor. Adding a
/// material is one row; `core { .. }` lists only the non-zero properties.
///
/// ```ignore
/// elements! {
///     Stone => {
///         color: (128, 128, 128),
///         core: { hardness: 180, density: 210 },
///     },
///     Copper => {
///         color: (184, 115, 51),
///         core: { conductivity: 240 },
///         specials: [HeatToElectricity(200)],
///     },
/// }
/// ```
macro_rules! elements {
    (
        $(
            $variant:ident => {
                color: ($r:expr, $g:expr, $b:expr),
                core: { $($core:tt)* }
                $(, specials: [ $( $svar:ident ( $sval:expr ) ),* $(,)? ] )?
                $(,)?
            }
        ),* $(,)?
    ) => {
        /// A built-in element handle. The discriminant is the element's
        /// [`ElementId`](crate::block::element::ElementId). Generated by
        /// [`elements!`](crate::macros::elements).
        #[repr(u16)]
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub enum El {
            $( $variant ),*
        }

        impl El {
            /// This element's stable id in a built-in registry.
            pub const fn id(self) -> $crate::block::element::ElementId {
                $crate::block::element::ElementId(self as u16)
            }
        }

        /// The built-in elements in id order.
        fn builtin_elements() -> Vec<$crate::block::element::Element> {
            vec![
                $(
                    $crate::block::element::Element {
                        name: stringify!($variant).into(),
                        color: ::raylib::prelude::Color::new($r, $g, $b, 255),
                        core: $crate::block::element::CoreProperties {
                            $($core)* ,
                            ..Default::default()
                        },
                        specials: {
                            #[allow(unused_mut)]
                            let mut specials: Vec<$crate::block::element::SpecialProperty> = Vec::new();
                            $( $( specials.push(
                                $crate::block::element::SpecialProperty::$svar($sval)
                            ); )* )?
                            specials.into_boxed_slice()
                        },
                    }
                ),*
            ]
        }
    };
}
pub(crate) use elements;

/// Define the built-in block table. Generates the [`Blk`] handle enum (each
/// variant's discriminant is its [`BlockId`](crate::block::registry::BlockId)) and
/// a `register_builtins()` that registers each block from its composition in id
/// order. The right-hand side is any expression yielding a
/// [`Composition`](crate::block::composition::Composition).
///
/// ```ignore
/// blocks! {
///     Air   => Composition::natural(&[]),
///     Stone => Composition::natural(&[El::Stone.id()]),
/// }
/// ```
macro_rules! blocks {
    ( $( $variant:ident => $comp:expr ),* $(,)? ) => {
        /// A built-in block handle. The discriminant is the block's
        /// [`BlockId`](crate::block::registry::BlockId). Generated by
        /// [`blocks!`](crate::macros::blocks).
        #[repr(u16)]
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub enum Blk {
            $( $variant ),*
        }

        impl Blk {
            /// This block's stable id in a built-in registry.
            pub const fn id(self) -> $crate::block::registry::BlockId {
                $crate::block::registry::BlockId(self as u16)
            }
        }

        /// Register every built-in block in id order. `Air` lands at id 0.
        fn register_builtins(registry: &mut $crate::block::registry::BlockRegistry) {
            $(
                let id = registry.register(stringify!($variant), $comp);
                debug_assert_eq!(id, Blk::$variant.id(), "builtin block id drift");
            )*
        }
    };
}
pub(crate) use blocks;
