//! Crate-wide declarative macros.
//!
//! These cover the table-driven patterns we expect to grow over time:
//! - [`elements!`] — the built-in element table; generates the [`El`](crate::block::element)
//!   id handles and `builtin_elements()`, so adding a material is a single row.
//!
//! The macro uses fully-qualified `::voxel_engine::...` paths so it expands
//! correctly regardless of what the call site has imported.

/// Define the built-in element table. Generates the [`El`] handle enum (each
/// variant's discriminant is its [`ElementId`](crate::block::element::ElementId),
/// fixed by declaration order) and a `builtin_elements()` constructor. Adding a
/// material is one row; `core { .. }` lists only the non-zero properties.
///
/// ```ignore
/// elements! {
///     Stone => {
///         color: (128, 128, 128),
///         core: { hardness: 180, density: 210 },
///     },
///     Copper => {
///         color: (184, 115, 51),
///         core: { conductivity: 240 },
///         specials: [HeatToElectricity(200)],
///     },
/// }
/// ```
macro_rules! elements {
    (
        $(
            $variant:ident => {
                color: ($r:expr, $g:expr, $b:expr),
                core: { $($cf:ident : $cv:expr),* $(,)? }
                $(, specials: [ $( $svar:ident ( $sval:expr ) ),* $(,)? ] )?
                $(,)?
            }
        ),* $(,)?
    ) => {
        /// A built-in element handle. The discriminant is the element's
        /// [`ElementId`](crate::block::element::ElementId). Generated by
        /// [`elements!`](crate::macros::elements).
        #[repr(u16)]
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub enum El {
            $( $variant ),*
        }

        impl El {
            /// This element's stable id in a built-in registry.
            pub const fn id(self) -> $crate::block::element::ElementId {
                $crate::block::element::ElementId(self as u16)
            }
        }

        /// The built-in elements in id order.
        fn builtin_elements() -> Vec<$crate::block::element::Element> {
            vec![
                $(
                    $crate::block::element::Element {
                        name: stringify!($variant).into(),
                        color: ::voxel_engine::Color::new($r, $g, $b, 255),
                        core: $crate::block::element::CoreProperties {
                            $($cf: $cv,)*
                            ..Default::default()
                        },
                        specials: {
                            #[allow(unused_mut)]
                            let mut specials: Vec<$crate::block::element::SpecialProperty> = Vec::new();
                            $( $( specials.push(
                                $crate::block::element::SpecialProperty::new(
                                    $crate::block::element::SpecialKind::$svar,
                                    $sval,
                                )
                            ); )* )?
                            specials.into_boxed_slice()
                        },
                    }
                ),*
            ]
        }
    };
}
pub(crate) use elements;
