//! movement.rs reads movement keys and advances the player each frame, resolving
//! collisions against the world. All speeds are expressed per second and scaled by
//! delta time so movement is frame-rate independent.
//!
//! The three control axes are generated by the [`axis!`](crate::macros::axis)
//! macro, which gives each a `sample` (read the keyboard) and a `signum` (turn the
//! direction into a scalar for vector math).
use voxel_engine::{Engine, Key, Vec3};

use crate::macros::axis;
use crate::math::Aabb;
use crate::player::{PLAYER_HALF, Player};
use crate::world::World;

const WALK_SPEED: f32 = 6.0; // units / second on the ground
const FLY_SPEED: f32 = 14.0; // units / second while flying
const GRAVITY: f32 = 24.0; // units / second^2
const JUMP_SPEED: f32 = 8.5; // initial upward velocity of a jump

axis!(AxisZ { Forward = W, Backward = S });
axis!(AxisX { Right = D, Left = A });
axis!(AxisY { Up = Space, Down = LeftShift });

/// The movement intent gathered from the keyboard for a single frame.
pub struct MoveInput {
    forward_back: AxisZ,
    left_right: AxisX,
    up_down: AxisY,
    jump: bool,
    toggle_fly: bool,
}

impl MoveInput {
    /// Sample the keyboard into a `MoveInput` for this frame.
    pub fn from_input(eng: &Engine) -> Self {
        Self {
            forward_back: AxisZ::sample(eng),
            left_right: AxisX::sample(eng),
            up_down: AxisY::sample(eng),
            jump: eng.is_key_down(Key::Space),
            toggle_fly: eng.is_key_pressed(Key::F),
        }
    }
}

/// Advance the player by one frame: build a movement delta from input + physics,
/// then apply it with per-axis collision resolution.
pub fn update_player(player: &mut Player, world: &World, input: &MoveInput, dt: f32) {
    // Toggling fly clears vertical velocity so you neither keep falling into the
    // new mode nor launch when you leave it.
    if input.toggle_fly {
        player.fly = !player.fly;
        player.velocity_y = 0.0;
    }

    let mut delta = Vec3::ZERO;

    // Horizontal movement is shared by both modes, but only worth computing when
    // a key is actually held — otherwise we'd run the yaw trig, a normalize, and
    // a scale every frame just to add a zero vector.
    if input.forward_back.is_active() || input.left_right.is_active() {
        let (forward, right) = player.movement_basis();
        let mut direction =
            forward * input.forward_back.signum() + right * input.left_right.signum();

        // `forward` and `right` are already unit length, so a single axis needs
        // no normalize. Only a diagonal (both axes active) would otherwise move
        // sqrt(2) too fast, so that's the only case we pay for the sqrt.
        if input.forward_back.is_active() && input.left_right.is_active() {
            direction = direction.normalize();
        }

        let speed = if player.fly { FLY_SPEED } else { WALK_SPEED };
        delta = direction * (speed * dt);
    }

    // Vertical movement is mode-specific, so each branch only runs its own work:
    // flying skips gravity and jumping entirely; walking skips the fly controls.
    if player.fly {
        delta.y = input.up_down.signum() * FLY_SPEED * dt;
    } else {
        // Apply the jump before deriving delta.y so it takes effect this frame.
        if input.jump && player.on_ground {
            player.velocity_y = JUMP_SPEED;
        }
        player.velocity_y -= GRAVITY * dt;
        delta.y = player.velocity_y * dt;
    }

    move_with_collision(player, world, delta);
}

/// Apply `delta` one axis at a time so the player slides along walls instead of
/// sticking, and detects when they land on the ground.
fn move_with_collision(player: &mut Player, world: &World, delta: Vec3) {
    let start = player.position;
    let mut pos = start;

    pos.x += delta.x;
    if world.collides(&Aabb::new(pos, PLAYER_HALF)) {
        pos.x = start.x;
    }

    pos.z += delta.z;
    if world.collides(&Aabb::new(pos, PLAYER_HALF)) {
        pos.z = start.z;
    }

    // Landing on something while moving down means we're grounded.
    player.on_ground = false;
    pos.y += delta.y;
    if world.collides(&Aabb::new(pos, PLAYER_HALF)) {
        if delta.y < 0.0 {
            player.on_ground = true;
        }
        pos.y = start.y;
        player.velocity_y = 0.0;
    }

    player.position = pos;
}
