//! movement.rs reads movement keys and advances the player each frame, resolving
//! collisions against the world. All speeds are expressed per second and scaled by
//! delta time so movement is frame-rate independent.
//!
//! Physics runs in `f64`: at |pos| ~100k an `f32` step of `6.0 * (1/4000)` is
//! smaller than the position's ULP and rounds to *zero* — the player stalls.
//! `dt` crosses the `f32`→`f64` boundary here, once, at the physics entry.
//!
//! The three control axes are generated by the [`axis!`](crate::macros::axis)
//! macro, which gives each a `sample` (read the keyboard) and a `signum` (turn the
//! direction into a scalar for vector math).
use voxel_engine::{DVec3, Engine, Key};

use crate::macros::axis;
use crate::math::{Aabb, WORLD_BORDER};
use crate::player::{PLAYER_HALF, Player};
use crate::world::World;

const WALK_SPEED: f64 = 6.0; // units / second on the ground
const FLY_SPEED: f64 = 14.0; // units / second while flying
const GRAVITY: f64 = 24.0; // units / second^2
const JUMP_SPEED: f64 = 8.5; // initial upward velocity of a jump

axis!(AxisZ { Forward = W, Backward = S });
axis!(AxisX { Right = D, Left = A });
axis!(AxisY { Up = Space, Down = LeftShift });

/// The movement intent gathered from the keyboard for a single frame.
pub struct MoveInput {
    forward_back: AxisZ,
    left_right: AxisX,
    up_down: AxisY,
    jump: bool,
    toggle_fly: bool,
}

impl MoveInput {
    /// Sample the keyboard into a `MoveInput` for this frame.
    pub fn from_input(eng: &Engine) -> Self {
        Self {
            forward_back: AxisZ::sample(eng),
            left_right: AxisX::sample(eng),
            up_down: AxisY::sample(eng),
            jump: eng.is_key_down(Key::Space),
            toggle_fly: eng.is_key_pressed(Key::F),
        }
    }
}

/// Advance the player by one frame: build a movement delta from input + physics,
/// then apply it with per-axis collision resolution.
pub fn update_player(player: &mut Player, world: &World, input: &MoveInput, dt: f32) {
    // The one f32 -> f64 physics boundary (see the module docs).
    let dt = dt as f64;

    // Toggling fly clears vertical velocity so you neither keep falling into the
    // new mode nor launch when you leave it.
    if input.toggle_fly {
        player.fly = !player.fly;
        player.velocity_y = 0.0;
    }

    let mut delta = DVec3::ZERO;

    // Horizontal movement is shared by both modes, but only worth computing when
    // a key is actually held — otherwise we'd run the yaw trig, a normalize, and
    // a scale every frame just to add a zero vector.
    if input.forward_back.is_active() || input.left_right.is_active() {
        let (forward, right) = player.movement_basis();
        let mut direction = forward * input.forward_back.signum() as f64
            + right * input.left_right.signum() as f64;

        // `forward` and `right` are already unit length, so a single axis needs
        // no normalize. Only a diagonal (both axes active) would otherwise move
        // sqrt(2) too fast, so that's the only case we pay for the sqrt.
        if input.forward_back.is_active() && input.left_right.is_active() {
            direction = direction.normalize();
        }

        let speed = if player.fly { FLY_SPEED } else { WALK_SPEED };
        delta = direction * (speed * dt);
    }

    // Vertical movement is mode-specific, so each branch only runs its own work:
    // flying skips gravity and jumping entirely; walking skips the fly controls.
    if player.fly {
        delta.y = input.up_down.signum() as f64 * FLY_SPEED * dt;
    } else {
        // Apply the jump before deriving delta.y so it takes effect this frame.
        if input.jump && player.on_ground {
            player.velocity_y = JUMP_SPEED;
        }
        player.velocity_y -= GRAVITY * dt;
        delta.y = player.velocity_y * dt;
    }

    move_with_collision(player, world, delta);
}

/// Apply `delta` one axis at a time so the player slides along walls instead of
/// sticking, and detects when they land on the ground.
///
/// Each axis clamps to ±[`WORLD_BORDER`] as it moves: the world border IS the
/// clamp. Movement (the only continuous position writer besides `/tp`, which
/// clamps the same way) can therefore never carry a coordinate past ±1e9, which
/// is the invariant [`block_coord`](crate::math::block_coord)'s overflow-free
/// i32 block math rests on.
fn move_with_collision(player: &mut Player, world: &World, delta: DVec3) {
    let start = player.position;
    let mut pos = start;

    pos.x = (pos.x + delta.x).clamp(-WORLD_BORDER, WORLD_BORDER);
    if world.collides(&Aabb::new(pos, PLAYER_HALF)) {
        pos.x = start.x;
    }

    pos.z = (pos.z + delta.z).clamp(-WORLD_BORDER, WORLD_BORDER);
    if world.collides(&Aabb::new(pos, PLAYER_HALF)) {
        pos.z = start.z;
    }

    // Landing on something while moving down means we're grounded.
    player.on_ground = false;
    pos.y = (pos.y + delta.y).clamp(-WORLD_BORDER, WORLD_BORDER);
    if world.collides(&Aabb::new(pos, PLAYER_HALF)) {
        if delta.y < 0.0 {
            player.on_ground = true;
        }
        pos.y = start.y;
        player.velocity_y = 0.0;
    }

    player.position = pos;
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::math::block_coord;

    /// Hold W, nothing else — the reported far-coordinate stall scenario.
    fn walk_forward() -> MoveInput {
        MoveInput {
            forward_back: AxisZ::Forward,
            left_right: AxisX::None,
            up_down: AxisY::None,
            jump: false,
            toggle_fly: false,
        }
    }

    /// Build a flat stone runway at `y = floor_y` under the given start, long
    /// enough for the walk tests, and stand the player on it. Terrain at these
    /// heights (well above the hills, below the island band) is air, so the
    /// runway is the only geometry.
    fn player_on_runway(world: &mut World, x: f64, z: f64) -> Player {
        let floor_y = 40;
        world.prepare_around(DVec3::new(x, floor_y as f64, z));
        let stone = world.registry().id_by_name("Stone").unwrap();
        let (bx, bz) = (block_coord(x), block_coord(z));
        for dx in -2..=12 {
            for dz in -2..=2 {
                world.set_block(bx + dx, floor_y, bz + dz, stone);
            }
        }
        // Feet on top of the runway: eye = feet + PLAYER_HALF.y.
        let mut player = Player::new(DVec3::new(x, (floor_y + 1) as f64 + PLAYER_HALF.y, z));
        player.yaw = 0.0; // forward = +X
        player
    }

    #[test]
    fn walking_at_1e8_advances_at_full_speed_at_4000_fps() {
        // The proven bug: at x = 1e8 an f32 position's ULP (8.0!) dwarfs the
        // per-frame step 6.0/4000 = 0.0015, so f32 movement added ZERO for a
        // whole second of frames. In f64, 4000 steps of dt = 1/4000 must cover
        // ~6 blocks (one second at WALK_SPEED).
        let mut world = World::generate();
        let start_x = 1.0e8 + 0.5;
        let mut player = player_on_runway(&mut world, start_x, 0.5);

        let dt = 1.0 / 4000.0;
        for _ in 0..4000 {
            let input = walk_forward();
            update_player(&mut player, &world, &input, dt);
        }

        let moved = player.position.x - start_x;
        assert!(
            (moved - 6.0).abs() < 0.05,
            "one second at WALK_SPEED must cover ~6 blocks, moved {moved}"
        );
        assert!(player.on_ground, "still standing on the runway");
        assert_eq!(player.position.z, 0.5, "no lateral drift");
    }

    #[test]
    fn movement_clamps_at_the_world_border_and_stays_finite() {
        // Near the border there is no terrain loaded (unloaded chunks read as
        // air), so fly there — the clamp is the border, not a wall of blocks.
        let mut world = World::generate();
        let start_x = WORLD_BORDER - 1000.0;
        world.prepare_around(DVec3::new(start_x, 300.0, 0.5));
        let mut player = Player::new(DVec3::new(start_x, 300.0, 0.5));
        player.fly = true;
        player.yaw = 0.0; // forward = +X, straight at the border

        // 2000 steps x 0.1s x 14 units/s = 2800 blocks of intent: crosses the
        // remaining 1000 and keeps pushing.
        for _ in 0..2000 {
            let input = walk_forward();
            update_player(&mut player, &world, &input, 0.1);
        }

        assert!(player.position.x.is_finite());
        assert_eq!(
            player.position.x, WORLD_BORDER,
            "the border clamps forward progress exactly"
        );
        assert!(player.position.y.is_finite() && player.position.z.is_finite());
        // And block conversion of the clamped position is still safe i32.
        assert_eq!(block_coord(player.position.x), 1_000_000_000);
    }
}
